meta_product_name: "Elsa"
meta_title: "Elsa - Travel longer. Travel More."
meta_description: "The more you spend, the more you earn with our instant caskback program."
meta_image: "sea-city-landscape-sky.jpg" # should exist in `app/assets/images/`
